---
# tasks file for apache

- name: Install httpd
  yum:
    name: httpd
    state: latest

- name: Configure httpd
  template:
    src: vhost.conf.j2
    dest: /etc/httpd/conf.d/vhost.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart httpd

- name: Start and enable httpd service
  service:
    name: httpd
    state: started
    enabled: true

- name: Create the application folder
  file:
    path: "/var/www/vhosts/{{ ansible_hostname }}"
    state: directory
    recurse: yes